
name: 'Terraform CI/CD Pipeline -EKS with Manual Approval and Deployment'

on:
  workflow_run:
    workflows: ["Terraform CI/CD Pipeline -EKS"]
    types:
      - completed 
    branches:
      - infra
  


env:
  TF_LOG: INFO
  TF_LOG_PATH: terraform.log
  TF_VERSION: 1.13.3 
  TF_WORKING_DIR: ./Infrastructure
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read
  pull-requests: write
  security-events: write
  issues: write


jobs:
#####################################
  #  Review and manual approval

  manual-approval:
    runs-on: ubuntu-latest
    name: 'Manual Approval'   
  
    steps:    
    - name: Await Manual Approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: kodcapsule
        minimum-approvals: 1
        issue-title: "Deploying v1.3.5 to prod from staging"
        issue-body: "Please approve or deny the deployment of version v1.3.5."
        exclude-workflow-initiator-as-approver: false
        
  
#####################################
  # Deployment infrastructure
#####################################

  deploy-infrastructure:
    runs-on: ubuntu-latest
    name: 'Terraform Apply'
    needs: manual-approval    
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}
    steps:      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: arn:aws:iam::650251710981:role/GithubWorkflowRole
          role-session-name: GitHubActions
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        id: init
        run: terraform init -backend=true -input=false

      - name: Generate Terraform Plan
        id: plan
        run: terraform plan -out=tfplan -no-color -input=false -lock-timeout=300s
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -input=false -lock-timeout=300s tfplan
        working-directory: ${{ env.TF_WORKING_DIR }}