name: Terraform EKS

on:
  push:
    branches:
      - infra
    paths:
        - 'Infrastructure/**'
  
  pull_request:
    branches:
      - main
      - infra
    paths:
        - 'Infrastructure/**'
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
env:
  TF_LOG: INFO
  TF_LOG_PATH: terraform.log
  TF_VERSION: 1.13.3
  TF_WORKSPACE: dev
  TF_WORKING_DIR: ./Infrastructure
  AWS_REGION: us-east-1
  

permissions:
  id-token: write
  contents: read
  pull-requests: write
  security-events: write

jobs:
#####################################
  # Stage 1: Format/Lint & Validation
#####################################
  format-validate-lint:
    runs-on: ubuntu-latest
    name: 'Format, Lint & Validation'
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2      

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        id: init
        run: terraform init -backend=false

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
     
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        
     
      - name: Terraform lint
        id: tflint
        uses: terraform-linters/setup-tflint@v6
        with:
          version: latest
          cache: true
          
      - name: show tflint version
        id: tflint-version
        run: tflint --version

      - name: Initialize TFLint (install plugins)
        id: tflint-init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}
      
      - name: Run TFLint
        id: tflint-run
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: tflint --format compact
        continue-on-error: true
      
      - name: Upload TFLint Report
        uses: actions/upload-artifact@v4 
        with:
          name: tflint-report-${{ github.sha }}  
          path: ${{ env.TF_WORKING_DIR }}/tflint-report.json  
          if-no-files-found: warn
  
      - name: Cache TFLint plugins
        uses: actions/cache@v4
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('infrastructure/.tflint.hcl') }}
          restore-keys: |
            ${{ runner.os }}-tflint-
#####################################
  # Stage 2: Static Code Analysis
#####################################
  # static-code-analysis:
  #   runs-on: ubuntu-latest
  #   name: 'Static Code Analysis'
  #   defaults:
  #     run:
  #       working-directory: ${{ env.TF_WORKING_DIR }}
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Terraform
  #       uses: hashicorp/setup-terraform@v3
  #       with:
  #         terraform_version: ${{ env.TF_VERSION }}

  #     - name: Terraform Init
  #       id: init
  #       run: terraform init -backend=false

  #     - name: Run SonarQube Scan
  #       uses: sonarsource/sonarcloud-github-action@master
  #       with:
  #         args: >
  #           -Dsonar.projectKey=your_project_key
  #           -Dsonar.organization=your_organization
  #           -Dsonar.host.url=https://sonarcloud.io
  #           -Dsonar.login=${{ secrets.SONAR_TOKEN }}
#####################################
  # Stage 3: Security Scans
#####################################
  Security-Scan:
    runs-on: ubuntu-latest
    name: 'Security Scanning' 
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tfsec Security Scanner
        id: tfsec-scan
        uses:  aquasecurity/tfsec-action@v1.0.0
        # run: |
        #   tfsec . --format sarif --out tfsec.sarif
        with:
           sarif_file: tfsec.sarif
           soft_fail: true
           github_token: ${{ secrets.GITHUB_TOKEN }}
          #  format: sarif
          #  working_directory: ./infrastructure
          
         
      # - name: Generate tfsec SARIF report
      #   id: generate-sarif
      #   run: |
      #     tfsec ./infrastructure --format sarif --out tfsec.sarif

      # - name: Upload tfsec Results
      #   uses: github/codeql-action/upload-sarif@v3
      #   if: always()
      #   with:
      #     sarif_file: tfsec.sarif 
      #     category: tfsec-security
      

      - name: tfsec PR Commenter
        uses: tfsec/tfsec-pr-commenter-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: run checkov scan
        id: checkov-scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
          output_format: 'json'          
          output_file_path: 'checkov-report.json'
          quiet: 'false'
          soft_fail: true

#####################################
  # Stage 4: policy enforcement 
#####################################
  policy-and-compliance:
    runs-on: ubuntu-latest
    name: 'Policy and Compliance'
    needs: format-validate-lint
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: arn:aws:iam::650251710981:role/GithubWorkflowRole
          role-session-name: GitHubActions
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        id: init
        run: terraform init -backend=true -input=false
        
      - name: Terraform Plan
        id: plan
        run: terraform plan  -out=tfplan  -no-color -input=false -lock-timeout=300s
        continue-on-error: false
    
      - name: Upload Terraform Plan Output
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ github.sha }}
          path: ${{ env.TF_WORKING_DIR }}/tfplan.json
          retention-days: 5

      - name: Save Terraform Plan Output
        id: show
        run: |
         terraform show -no-color tfplan > plan.txt
         echo "stdout<<EOF" >> $GITHUB_OUTPUT
         cat plan.txt >> $GITHUB_OUTPUT
         echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment Terraform Plan on PR       
        if: github.event_name == 'pull_request'        
        uses: marocchino/sticky-pull-request-comment@v2        
        with:
          header: terraform plan result
          message: |
            ```terraform
            ${{ steps.show.outputs.stdout }}
            ```
      
      - name: download Opa
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest

      - name: run OPA test
        run: opa test .
      # - name: Validate Terraform with OPA
        # run: |
        #   my test command |
        #      opa val --fail-defined \
        #      --stdin-input \
        #       --data ./Infrastructure/policies \
                             
      #     opa eval --format pretty --data https://raw.githubusercontent.com/open-policy-agent/contrib/main/terraform/rego/terraform.rego \
      #     'data.terraform.deny' --input <(terraform show -json)

#####################################
  # Stage 5: Unit Testing  
#####################################
  unit-testing:
    runs-on: ubuntu-latest
    name: 'Unit Testing'
    needs: format-validate-lint    
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}
    steps:  
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        id: init
        run: terraform init -backend=false

      - name: Setup Go (for Terratest)
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'



      - name: Install Terratest Dependencies
        working-directory: ./infrastructure
        run: |
          go mod init terraform-tests || true
          go get github.com/gruntwork-io/terratest/modules/terraform
          go get github.com/stretchr/testify/assert
          go mod tidy

      - name: Run Terratest Unit Tests
        working-directory: ./infrastructure
        run: go test -v -timeout 30m
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          TF_VAR_environment: test
       

      # - name: Run Terraform Native Tests



      # - name: Run terraform-compliance tests
      #   uses: terraform-compliance/terraform-compliance-action@v1.0.6
      #   with:
      #     tf_root_path: .
      #     features_path: ./tests/features
      #     output_format: pretty
      #     continue_on_failure: false
      


#####################################
  # Stage 6: Plan  Terraform Plan
#####################################


#####################################
  # Stage 7: Review and manual approval
#####################################


#####################################
  # Stage 8: Deployment - Terraform Apply
#####################################

  # terraform-apply:
#  runs-on: ubuntu-latest
#  name: 'Terraform Apply'
#     # needs: terraform-plan-and-opa-scan
#     if: github.ref == 'refs/heads/main' && github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply')
#     defaults:
#       run:
#         working-directory: ${{ env.TF_WORKING_DIR }}
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v5.1.0
#         with:
#           role-to-assume: arn:aws:iam::650251710981:role/GithubWorkflowRole
#           role-session-name: GitHubActions
#           aws-region: ${{ env.AWS_REGION }}